language: node_js
node_js:
  - "10.16.3"
addons:
  chrome: stable
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
script:
  - ng lint
  - ng serve &
  - npm test -- --watch false --browsers ChromeHeadless
  - npm run e2e-update-webdriver
  - npm run e2e-travis
