language: node_js
node_js:
  - "10.16.3"
addons:
  chrome: stable
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng serve &
  - npm test -- --watch false --browsers ChromeHeadless
  - npm run e2e-update-webdriver
  - npm run e2e-travis
  - npm run build -- --base-href https://xgirma.github.io/unit-vs-e2e
  - npx angular-cli-ghpages --dir=dist/unit-vs-e2e
