name: NodeCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install root, @angular/cli
      run: |
        npm ci
        npm install -g @angular/cli
      env:
        CI: true
    - name: lint, build, unit and e2e test
      run: |
        npm run lint
        npm run build
        npm run test -- --configuration=ci --watch=false --code-coverage
        npm run webdriver-update
        npm run e2e -- --configuration=ci
